Improves 'Schedule' tag handling
cfpb/hubot-aws-cfpb pull request #25
Opened 2017-03-31 21:14 UTC by marcesher

1. Adds the ability to modify the 'Schedule' tag via new `schedule` and `unschedule commands`.

2. Removes a schedule when an instance is stopped, so that our scheduler doesn't start it.

3. Adds the default 8 AM to 6 PM schedule when an instance is started or extended

2017-04-03 11:52 UTC, marcesher commented
replaced @imuchnik with @vccabral as reviewer b/c Irina won't be available to review for several weeks.

2017-04-04 14:07 UTC, vccabral commented
LGTM

2017-04-04 19:39 UTC, contolini requested changes

2017-04-04 19:39 UTC, contolini commented on package.json
> +  "version": "1.0.9",
Bump the minor version (`1.0.8` > `1.1.0`) because this change adds backward-compatible features.

2017-04-04 20:15 UTC, contolini commented
@marcesher also please add some notes to readme about how to use the scheduling feature

2017-04-04 20:40 UTC, contolini commented on scripts/ec2/schedule.coffee
> +      if i and not i.match(/^--/)
This is picking up the time values, you could do something like `if i and not i.match(/^\-\-/) and i.length > 5`.

2017-04-04 21:09 UTC, contolini requested changes

2017-04-04 21:09 UTC, contolini commented on scripts/ec2/schedule.coffee
> +      if i and not i.match(/^--/)
Actually just checking if the string starts with `i-` is much simpler: `if i and i.match(/^i-/)`

2017-04-04 23:13 UTC, contolini approved these changes

2017-04-04 23:16 UTC, merged